name: datascience_dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  
  - click
  - python-dotenv>=0.5.1
  - Sphinx
  
  - flask
  - marshmallow
  - gunicorn

  - pre-commit
  - black
  - isort
  - flake8
  - mypy